name = "gleamdb"
version = "2.5.0"
description = "A high-performance, analytical Datalog engine for Gleam"
licences = ["Apache-2.0"]

[dependencies]
gleam_stdlib = ">= 0.34.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_otp = ">= 1.2.0 and < 2.0.0"
wisp = ">= 2.2.0 and < 3.0.0"
lustre = ">= 5.6.0 and < 6.0.0"
mist = ">= 5.0.4 and < 6.0.0"
gleam_http = ">= 4.3.0 and < 5.0.0"
simplifile = ">= 2.3.2 and < 3.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0"
