name = "gclaw"
version = "1.0.0"

[dependencies]
gleam_stdlib = "0.69.0"
gleam_erlang = "1.3.0"
gleam_otp = "1.2.0"
gleam_http = "4.3.0"
gleam_hackney = "1.3.3"
gleam_json = "3.1.0"
simplifile = "2.3.0"

[dev-dependencies]
gleeunit = "1.9.0"
